### PR TITLE
Merges and Post-Processes Bifrost Data into Moonbeam Crowdloan Data

### PR DESCRIPTION
**Pull request by albertov19**
This adds the contributions from Bifrost to the Moonbeam Crowdloan Data JSON. The data was compiled by doing the following:

- Remove Bifrost as a contributor from the Moonbeam Data
- Go through each Bifrost Contribution
- If the contributors address exists in Moonbeam Data:
    * Remove the memo
    * Adds the Bifrost contribution amount to the Moonbeam data contribution amount
    * Removes that contribution from the Bifrost Data
- After it goes through all, it concatenates the remaining Bifrost contributions to Moonbeam contributions
- Calculates the new Moonbeam data contribution amount
- Compares it with the total_raised (previous amount must match the new amount)

### CODE REVIEW

**Comment by girazoki** [comment]
It seems to me as if there is some Bifrost data that is nor merged. Examples:

15rVyBCy8kBxYvB6ZzcCGmLi1ti4tT1N25bw6BP3M8exQmJL

15aF6Zkzm9xamEtG9rdUcm9fq23ocLnt9aV3yLqnh7qBJfGX

Maybe there is some repeated data within the bifrost file that does not have a match in the crowdloan file, and therefore they dont get merged?

**Comment by albertov19** [comment]
The processing script was modified to handle duplicate data within the Bifrost file. This is the new set of operations:

- Remove Bifrost as a contributor from the Moonbeam Data
- Go through each Bifrost Contribution
- If the contributors address exists in Moonbeam Data:
    * Check wether the memos are different, if so, remove the memo from the Moonbeam Data (to avoid conflicts)
    * Adds the Bifrost contribution amount to the Moonbeam data contribution amount
    * Removes that contribution from the Bifrost Data
- If the contributor does not exist in Moonbeam Data:
    * Add it into the Moonbeam Data (the order of operations ensures that duplicates in the Bifrost data are handled by the "if" statement mentioned before)
- Calculates the new Moonbeam data contribution amount
- Compares it with the total_raised (previous amount **must match** the new amount)

**Review by girazoki — APPROVED** [review]
its an approval for me. I verified several times the file, the scripts that generated it and the initialization process

**Comment by girazoki** [comment]
@crystalin @notlesh Tim has verified and reached the same file through other means, so I think we are good to go. Dou you guys want to verify the file? This is the one that should go into Moonlama for our tests

**Review by purestaketdb — APPROVED** [review]
Bifrost summary starts with 348 entries of which 4 have bad ethereum address that are blanked. 66 are duplicated internal to the summary, leaving 282.

Of the 282 remaining, 95 are found in the Moonbeam file and add only the contribution and 187 records are added to the extract. 

The sum of the Bifrost contribution remains the same before and after the merge (708146266594142), as does the overall sum of the crowdloan (357599313927924796).

**Pull request merged**
